# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationusertype',
            old_name='type',
            new_name='usertype',
        ),
    ]
