# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserType',
            new_name='RelationUserType',
        ),
    ]
