# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('medium', models.CharField(choices=[('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call'), ('Inbound Email', 'Inbound Email'), ('Outbound Email', 'Outbound Email'), ('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call')], max_length=255)),
                ('medium_status', models.CharField(choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], max_length=10)),
                ('contact_person', models.CharField(max_length=255)),
                ('remarks', models.TextField(max_length=999)),
                ('to_lead', models.BooleanField(default=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='lead.Process')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesStage',
            fields=[
                ('substage', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sales_stage', models.CharField(choices=[('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('Approaching', 'Approaching')], max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_sales', to='communication.Clientlist')),
            ],
        ),
        migrations.CreateModel(
            name='SalesSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_substage', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_salessub', to='communication.Clientlist')),
                ('substage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_stage', to='communication.SalesStage')),
            ],
        ),
    ]
