# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('medium', models.CharField(choices=[('In', 'Inbound Call'), ('Out', 'Outbound Call'), ('Email', 'Email'), ('Sms', 'SMS'), ('Visit', 'Visit')], default='Email', max_length=10)),
                ('medium_status', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('Suspecting', 'Suspecting'), ('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('Approach', 'Approach'), ('Job_Posting', 'Job Posting'), ('Job_Edit', 'Job Edit'), ('Approval', 'Approval'), ('Invoicing', 'Invoicing'), ('Payment_Follow up', 'Payment Follow up'), ('Payment_Collection', 'Payment Collection'), ('General_Query', 'General Query'), ('Value_Proposition', 'Value Proposition'), ('Password_Reset', 'Password Reset')], default='General_Query', max_length=50)),
                ('remarks', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('remainder_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='communication', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
