# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationitem',
            name='purpose',
            field=models.CharField(choices=[('Suspecting', 'Suspecting'), ('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('Approach', 'Approach'), ('Job_Posting', 'Job Posting'), ('Job_Edit', 'Job Edit'), ('Approval', 'Approval'), ('Invoicing', 'Invoicing'), ('Payment_Follow_up', 'Payment Follow up'), ('Payment_Collection', 'Payment Collection'), ('General_Query', 'General Query'), ('Value_Proposition', 'Value Proposition'), ('Password_Reset', 'Password Reset')], default='General_Query', max_length=50),
        ),
    ]
