# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlist',
            old_name='to_lead',
            new_name='from_lead',
        ),
    ]
