# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20171124_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunicationItem',
            new_name='Item',
        ),
    ]
