# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20171220_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='stage',
            field=models.CharField(choices=[('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('C', 'C'), ('D', 'D')], default='Suspecting', max_length=50),
        ),
    ]
