# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20171127_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purpose',
            field=models.CharField(choices=[('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('Approach', 'Approach'), ('Job Posting', 'Job Posting'), ('Job Edit', 'Job Edit'), ('Approval', 'Approval'), ('Invoicing', 'Invoicing'), ('Payment Follow up', 'Payment Follow up'), ('Payment Collection', 'Payment Collection'), ('General Query', 'General Query'), ('Value Proposition', 'Value Proposition'), ('Password Reset', 'Password Reset')], default='General_Query', max_length=50),
        ),
    ]
