# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_process_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='birthvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='process',
            name='firstval',
            field=models.IntegerField(default=110),
        ),
        migrations.AddField(
            model_name='process',
            name='secondval',
            field=models.IntegerField(default=110),
        ),
    ]
