# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20171220_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='birthvalue',
        ),
        migrations.RemoveField(
            model_name='process',
            name='firstval',
        ),
        migrations.RemoveField(
            model_name='process',
            name='secondval',
        ),
    ]
