# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20171230_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlist',
            name='owner',
        ),
    ]
