# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20171220_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='purpose',
            field=models.CharField(choices=[('Approach', 'Approach'), ('Job Posting', 'Job Posting'), ('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('Approval', 'Approval'), ('Payment Collection', 'Payment Collection'), ('General Query', 'General Query')], default='General_Query', max_length=50),
        ),
        migrations.AlterField(
            model_name='process',
            name='remainder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='stage',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='Suspecting', max_length=50),
        ),
    ]
