# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_remove_clientlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesstage',
            name='substage',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
