# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_auto_20171231_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_substage', models.CharField(max_length=100)),
                ('substage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_stage', to='communication.SalesStage')),
            ],
        ),
    ]
