# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_salessub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detaillist',
            name='client',
        ),
        migrations.AddField(
            model_name='clientlist',
            name='contact_person',
            field=models.CharField(default='Foo Bar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientlist',
            name='medium',
            field=models.CharField(choices=[('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call'), ('Inbound Email', 'Inbound Email'), ('Outbound Email', 'Outbound Email'), ('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call')], default='Inbound Call', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientlist',
            name='medium_status',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='Successful', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientlist',
            name='remarks',
            field=models.TextField(default='This is good.', max_length=999),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Detaillist',
        ),
    ]
