# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_process_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('General Query', 'General Query')], default='Suspecting', max_length=50)),
                ('purpose_description', models.CharField(default='Purpose description here', max_length=100)),
                ('approached_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-approached_date',),
            },
        ),
        migrations.RemoveField(
            model_name='process',
            name='purpose',
        ),
    ]
