# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_auto_20171221_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stageaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(default='Sample action', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
        migrations.AddField(
            model_name='process',
            name='stage',
            field=models.CharField(choices=[('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('Approaching', 'Approaching')], default='Suspecting', max_length=50),
        ),
        migrations.AddField(
            model_name='stageaction',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Process'),
        ),
    ]
