# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_auto_20180102_1632'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesstage',
            unique_together=set([]),
        ),
    ]
