# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_auto_20180102_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessub',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_salessub', to='communication.Clientlist'),
            preserve_default=False,
        ),
    ]
