# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_auto_20171221_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salestage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Suspecting', 'Suspecting'), ('Prospecting', 'Prospecting'), ('Approaching', 'Approaching')], default='Suspecting', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='process',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='stageaction',
            name='process',
        ),
    ]
