# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_auto_20171221_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestage',
            name='stage',
            field=models.CharField(default='Suspecting', max_length=15),
        ),
    ]
