# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_auto_20171221_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageaction',
            name='salestage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communication.Salestage'),
            preserve_default=False,
        ),
    ]
