# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0016_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Universe',
        ),
    ]
