# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0017_auto_20171222_0722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Universe',
            new_name='Celestial',
        ),
    ]
