# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import polymorphic_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('communication', '0018_auto_20171222_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
                'verbose_name': 'Tree node',
                'verbose_name_plural': 'Tree nodes',
            },
        ),
        migrations.RemoveField(
            model_name='celestial',
            name='parent',
        ),
        migrations.CreateModel(
            name='CategoryNode',
            fields=[
                ('basetreenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='communication.BaseTreeNode')),
                ('opening_title', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category node',
                'verbose_name_plural': 'Category nodes',
            },
            bases=('communication.basetreenode',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TextNode',
            fields=[
                ('basetreenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='communication.BaseTreeNode')),
                ('extra_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text node',
                'verbose_name_plural': 'Text nodes',
            },
            bases=('communication.basetreenode',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Celestial',
        ),
        migrations.AddField(
            model_name='basetreenode',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='communication.BaseTreeNode', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='basetreenode',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_communication.basetreenode_set+', to='contenttypes.ContentType'),
        ),
    ]
