# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0020_auto_20171225_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateNode',
            fields=[
                ('basetreenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='communication.BaseTreeNode')),
                ('extra_text', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Date node',
                'verbose_name_plural': 'Date nodes',
            },
            bases=('communication.basetreenode',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='textnode',
            name='basetreenode_ptr',
        ),
        migrations.DeleteModel(
            name='TextNode',
        ),
    ]
