# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0021_auto_20171226_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datenode',
            old_name='extra_text',
            new_name='date',
        ),
    ]
