# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0022_auto_20171226_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryNode',
            new_name='DescriptionNode',
        ),
        migrations.AlterModelOptions(
            name='descriptionnode',
            options={'verbose_name': 'Description node', 'verbose_name_plural': 'Description nodes'},
        ),
    ]
