# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0023_auto_20171227_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptionnode',
            old_name='opening_title',
            new_name='description',
        ),
    ]
