# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=3)),
                ('unit', models.PositiveIntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], max_length=20)),
                ('bulk', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
