# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='process',
            name='stage',
            field=models.PositiveIntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='process',
            name='service',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('C', 'C'), ('D', 'D')], max_length=3),
        ),
    ]
