# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
