# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20171124_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.PositiveIntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(1)]),
        ),
    ]
