# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_auto_20171221_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='service',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software')], max_length=15),
        ),
    ]
