# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_auto_20171221_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='process',
            name='tax_percent',
            field=models.PositiveIntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(1), rest_framework.compat.MaxValueValidator(25)]),
        ),
    ]
