# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_auto_20171223_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherNode',
            fields=[
                ('basetreenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lead.BaseTreeNode')),
                ('description', models.CharField(max_length=200, verbose_name='Descriptionn')),
                ('remainder_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AnotherNode node',
                'verbose_name_plural': 'Another nodes',
            },
            bases=('lead.basetreenode',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
