# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_auto_20171224_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynode',
            name='opening_title',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
    ]
