# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_auto_20171225_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetreenode',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='basetreenode',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='categorynode',
            name='basetreenode_ptr',
        ),
        migrations.RemoveField(
            model_name='textnode',
            name='basetreenode_ptr',
        ),
        migrations.DeleteModel(
            name='BaseTreeNode',
        ),
        migrations.DeleteModel(
            name='CategoryNode',
        ),
        migrations.DeleteModel(
            name='TextNode',
        ),
    ]
